baseURL = "https://msarfrazhameed.github.io/"
title = "Sarfraz Hameed | Portfolio"
theme = "blowfish"

[params]
  defaultAppearance = "dark"
  colorScheme = "cyberpunk"
  logo = "images/sar_profile.jpg"

[params.homepage]
    layout = "background"
    showRecent = true
    showRecentItems = 5
    cardView = true
    homepageImage = "images/background.jpg" # THIS is the line Blowfish was waiting for!

  [params.article]
    showDate = false
    showReadingTime = false

[author]
  name = "Sarfraz Hameed"
  image = "images/sar_profile.jpg" # THIS is the important line!
  headline = "Cybersecurity & Agentic AI Developer"
  bio = "Building automated zero-trust architectures and RAG-based AI agents."

  links = [
    { email = "mailto:sarfrazhmeed@gmail.com" },
    { github = "https://github.com/" },
    { linkedin = "https://linkedin.com/" }
  ]
  [menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
   